USE [master]
GO
/****** Object:  Database [byteknight]    Script Date: 02/07/2012 12:26:55 ******/
CREATE DATABASE [byteknight] ON  PRIMARY 
( NAME = N'byteknight', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\byteknight.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'byteknight_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\byteknight_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'byteknight', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [byteknight].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [byteknight] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [byteknight] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [byteknight] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [byteknight] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [byteknight] SET ARITHABORT OFF 
GO
ALTER DATABASE [byteknight] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [byteknight] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [byteknight] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [byteknight] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [byteknight] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [byteknight] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [byteknight] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [byteknight] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [byteknight] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [byteknight] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [byteknight] SET  ENABLE_BROKER 
GO
ALTER DATABASE [byteknight] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [byteknight] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [byteknight] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [byteknight] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [byteknight] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [byteknight] SET  READ_WRITE 
GO
ALTER DATABASE [byteknight] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [byteknight] SET  MULTI_USER 
GO
ALTER DATABASE [byteknight] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [byteknight] SET DB_CHAINING OFF 